vich_uploader:
    db_driver: orm
    metadata:
        type: attribute
    mappings:
        personne_avatar:
            uri_prefix: /images/eleves
            upload_destination: '%kernel.project_dir%/public/uploads/images/eleves'
            # Will rename uploaded files using a uniqueid as a prefix.
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
